function combinational(name,design,declarations,connection,stimulus,explanation){
 return {name,design,explanation,testbench:'`timescale 1ns/1ps\nmodule tb;\n'+declarations+'\n  '+connection+'\n\n  initial begin\n    $dumpfile("signal.vcd");\n    $dumpvars(0, tb);\n'+stimulus+'\n    $finish;\n  end\nendmodule\n'};
}
export const examples={
 gates:combinational('Logic gates',`// Six basic gates, one pair of inputs.\nmodule logic_gates (\n  input a, b,\n  output and_y, or_y, xor_y,\n  output nand_y, nor_y, xnor_y\n);\n  assign and_y  = a & b;\n  assign or_y   = a | b;\n  assign xor_y  = a ^ b;\n  assign nand_y = ~(a & b);\n  assign nor_y  = ~(a | b);\n  assign xnor_y = ~(a ^ b);\nendmodule\n`,'  reg a, b;\n  wire and_y, or_y, xor_y, nand_y, nor_y, xnor_y;\n  integer i;','logic_gates dut (a, b, and_y, or_y, xor_y, nand_y, nor_y, xnor_y);','    for (i = 0; i < 4; i = i + 1) begin\n      {a, b} = i;\n      #20;\n    end','AND is high when both inputs are high. XOR is high when the inputs differ. Compare all six outputs along the same timeline.'),
 half:combinational('Half adder',`// Add two one-bit numbers.\nmodule half_adder (\n  input a, b,\n  output sum, carry\n);\n  assign sum   = a ^ b;\n  assign carry = a & b;\nendmodule\n`,'  reg a, b;\n  wire sum, carry;\n  integer i;','half_adder dut (.a(a), .b(b), .sum(sum), .carry(carry));','    for (i = 0; i < 4; i = i + 1) begin\n      {a, b} = i;\n      #20;\n    end','A half adder adds two bits. The sum is XOR; the carry is AND. When a = b = 1, the two-bit answer is 10.'),
 full:combinational('Full adder',`// A full adder combines three one-bit inputs.\n// The result is the two-bit value {carry, sum}.\nmodule full_adder (\n  input  a, b, cin,\n  output sum, carry\n);\n  wire partial_sum;\n  wire carry_ab, carry_cin;\n\n  // First, add a and b.\n  assign partial_sum = a ^ b;\n  assign carry_ab    = a & b;\n\n  // Then include the carry input.\n  assign sum       = partial_sum ^ cin;\n  assign carry_cin = partial_sum & cin;\n  assign carry     = carry_ab | carry_cin;\nendmodule\n`,'  reg a, b, cin;\n  wire sum, carry;\n  integer i;','full_adder dut (.a(a), .b(b), .cin(cin),\n                  .sum(sum), .carry(carry));','    // Try all 8 combinations, 10 ns apart.\n    for (i = 0; i < 8; i = i + 1) begin\n      {a, b, cin} = i;\n      #10;\n      $display("a=%b b=%b cin=%b | sum=%b carry=%b",\n               a, b, cin, sum, carry);\n    end','A full adder adds a, b, and carry-in. The sum is high for an odd number of 1s; carry is high when at least two inputs are 1.'),
 mux:combinational('4:1 multiplexer',`// Select one of four data inputs.\nmodule mux4 (\n  input [3:0] d,\n  input [1:0] sel,\n  output y\n);\n  assign y = d[sel];\nendmodule\n`,'  reg [3:0] d;\n  reg [1:0] sel;\n  wire y;\n  integer i;','mux4 dut (.d(d), .sel(sel), .y(y));',`    d = 4'b1010;\n    for (i = 0; i < 4; i = i + 1) begin\n      sel = i; #10;\n    end\n    d = 4'b0101;\n    for (i = 0; i < 4; i = i + 1) begin\n      sel = i; #10;\n    end`,'The two select bits choose which input reaches y: 00 selects d[0], 01 selects d[1], 10 selects d[2], and 11 selects d[3].'),
 decoder:combinational('2:4 decoder',`// One-hot decoder with an enable input.\nmodule decoder2 (\n  input [1:0] a,\n  input en,\n  output [3:0] y\n);\n  assign y = en ? (4'b0001 << a) : 4'b0000;\nendmodule\n`,'  reg [1:0] a;\n  reg en;\n  wire [3:0] y;\n  integer i;','decoder2 dut (.a(a), .en(en), .y(y));','    en = 0; a = 0; #10;\n    en = 1;\n    for (i = 0; i < 4; i = i + 1) begin\n      a = i; #15;\n    end\n    en = 0; #10;','When enabled, exactly one output bit is high. The input a gives its position. With en = 0, every output is low.'),
 dff:{name:'D flip-flop',explanation:'Q captures D at each rising clock edge. An asynchronous reset clears Q immediately. Move the time cursor across a clock edge to see the change.',design:`// Positive-edge D flip-flop, asynchronous reset.\nmodule d_flip_flop (\n  input clk, rst, d,\n  output reg q\n);\n  always @(posedge clk or posedge rst) begin\n    if (rst)\n      q <= 1'b0;\n    else\n      q <= d;\n  end\nendmodule\n`,testbench:'`timescale 1ns/1ps\nmodule tb;\n  reg clk = 0, rst = 1, d = 0;\n  wire q;\n  d_flip_flop dut (clk, rst, d, q);\n\n  always #5 clk = ~clk;\n\n  initial begin\n    $dumpfile("signal.vcd");\n    $dumpvars(0, tb);\n    #12 rst = 0;\n    #6  d = 1;\n    #14 d = 0;\n    #16 d = 1;\n    #12 rst = 1;\n    #7  rst = 0;\n    #23 $finish;\n  end\nendmodule\n'},
 jk:{name:'JK flip-flop',explanation:'At a rising clock edge: 00 holds Q, 01 resets it, 10 sets it, and 11 toggles it. Reset is asynchronous in this example.',design:`module jk_flip_flop (\n  input clk, rst, j, k,\n  output reg q\n);\n  always @(posedge clk or posedge rst) begin\n    if (rst) q <= 1'b0;\n    else case ({j, k})\n      2'b00: q <= q;\n      2'b01: q <= 1'b0;\n      2'b10: q <= 1'b1;\n      2'b11: q <= ~q;\n    endcase\n  end\nendmodule\n`,testbench:'`timescale 1ns/1ps\nmodule tb;\n  reg clk = 0, rst = 1, j = 0, k = 0;\n  wire q;\n  jk_flip_flop dut (clk, rst, j, k, q);\n  always #5 clk = ~clk;\n  initial begin\n    $dumpfile("signal.vcd");\n    $dumpvars(0, tb);\n    #12 rst = 0;\n    #10 {j, k} = 2\'b10;\n    #20 {j, k} = 2\'b00;\n    #20 {j, k} = 2\'b01;\n    #20 {j, k} = 2\'b11;\n    #40 $finish;\n  end\nendmodule\n'},
 counter:{name:'4-bit counter',explanation:'The counter increments on rising clock edges while en is high. It holds when en is low, wraps from 15 to 0, and clears when reset is asserted.',design:`// Enabled synchronous counter with async reset.\nmodule counter4 (\n  input clk, rst, en,\n  output reg [3:0] count\n);\n  always @(posedge clk or posedge rst) begin\n    if (rst)\n      count <= 4'b0000;\n    else if (en)\n      count <= count + 1'b1;\n  end\nendmodule\n`,testbench:'`timescale 1ns/1ps\nmodule tb;\n  reg clk = 0, rst = 1, en = 0;\n  wire [3:0] count;\n  counter4 dut (clk, rst, en, count);\n  always #5 clk = ~clk;\n  initial begin\n    $dumpfile("signal.vcd");\n    $dumpvars(0, tb);\n    #12 rst = 0; en = 1;\n    #60 en = 0;\n    #20 en = 1;\n    #120 $finish;\n  end\nendmodule\n'}
};
